### ISSUE TITLE
Additional weather sources

### ISSUE THREAD

**Issue by open-meteo** [mikesprague/localweather-io#219]
Hi,

I was just browsing Github and stumbled across your project. I created a free weather API. Would you be interested to integrate an additional weather provider? Let me know if you need additional weather variables or features.

Best, Jeff

**Comment by mikesprague** [comment]
I somehow missed this but I would be more than happy/willing to check out your API if you can provide some links or any additional info that would be helpful. 

With Dark Sky API fully shutting down March 2023, my plan was to convert this to use OpenWeatherMap. Mainly because I was aware of the service and they have a generous free tier. 

I did some work this weekend to update the build system and move it to another hosting provider and will be making the API updates soon.

Thanks again for reaching out and sorry for not seeing this or responding until now.

**Comment by mikesprague** [comment]
Never got a reply to my (months late) reply so closing. Feel free to reopen.
